CREATE TABLE orders
(
    id         UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items
(
    id       UUID PRIMARY KEY,
    order_id UUID
        REFERENCES orders ON DELETE CASCADE
);